test 5

diff --git a/.github/workflows/git-ci.yml b/.github/workflows/git-ci.yml
--- a/.github/workflows/git-ci.yml
+++ b/.github/workflows/git-ci.yml
@@ -29,11 +29,11 @@ jobs:
       - name: Build the Docker Image
         run: |
               docker build . --file Dockerfile --tag server:$(date +%s)
-              if [ $? eq 0 ]
+              if [ $? -eq 0 ]
               then 
-                echo "OooooooooooooooooooooooooooooooooooooK" 
+                echo "Ok Giorgio" 
               else  
-                echo "FAILeddddddddddddddddddddddddddddddddddddd"
+                echo "FAIL Giorgio"
               fi
 
       # Runs a set of commands using the runners shell
