test 2

diff --git a/.github/workflows/git-ci.yml b/.github/workflows/git-ci.yml
--- a/.github/workflows/git-ci.yml
+++ b/.github/workflows/git-ci.yml
@@ -28,12 +28,7 @@ jobs:
       # Runs a single command using the runners shell
       - name: Build the Docker Image
         run: |
-              if [docker build . --file Dockerfile --tag server:$(date +%s)]
-              then 
-                echo "OK" 
-              else  
-                echo "FAIL"
-              fi
+              docker build . --file Dockerfile --tag server:$(date +%s) || { echo 'my_command failed' ; exit 1; }
 
       # Runs a set of commands using the runners shell
       - name: Discord Message
